version: "3.6"
services:
  postgres16:
    build: ../../images/postgres16
    environment:
      - POSTGRES_PASSWORD=Postgres.123
      - DATABASE_USER=protheus
      - DATABASE_PASS=Protheus.123
      - DATABASE_NAME=p1212510mntdbexp
    volumes:
      - "../../:/local"
      - "postgres16:/var/lib/postgresql/data"
    ports:
      - "5432"
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2GB
  dbaccess:
    build: ../../images/dbaccess
    command: ["bash", "/local/tools/dbaccess.sh"]
    environment:
      - TOTVS_HOME=/local/data/totvs/
      - DBACCESS_HOME=/local/data/totvs/dbaccess/multi/
      - LICENSE_SERVER=${LICENSE_SERVER:-localhost}
      - LICENSE_PORT=${LICENSE_PORT:-5555}
      - DBACCESS_DRIVER=postgres
      - DBACCESS_ALIAS=1212510_bra
    volumes:
      - "../../:/local"
      - "../../data/totvs/dbaccess/configures/odbc.ini:/etc/odbc.ini"
      - "../../data/totvs/dbaccess/configures/tnsnames.ora:/opt/oracle/instantclient_21_5/network/admin/tnsnames.ora"
    ports:
      - "7890"
    depends_on:
      - postgres16

  protheus:
    build: ../../images/protheus
    command: ["bash", "/local/tools/protheus.sh"]
    environment:
      - TOTVS_HOME=/local/data/totvs/
      - PROTHEUS_HOME=/local/data/totvs/protheus/
      - APPSERVER_HOME=/local/data/totvs/appserver/
      - DBSERVER=dbaccess
      - DBPORT=7890
      - DBDATABASE=postgres
      - DBALIAS=1212510_bra
    volumes:
      - "../../:/local"
    ports:
      - "8080"
    depends_on:
      - dbaccess

volumes:
  postgres16: {}
