# =====================================================================
# Best Practice Recommendations for SQL Server on Linux
# =====================================================================

[sqlagent]
enabled = false

[telemetry]
customerfeedback = false
userrequestedlocalauditdirectory = /var/opt/mssql/audit

# =====================================================================
# Performance Tuning
# =====================================================================

[memory]
# Define um limite de memória para o SQL Server.
# O valor é em MB. Recomenda-se usar ~80% da memória disponível para o contêiner.
# Este valor pode ser sobrescrito pela variável de ambiente MSSQL_MEMORY_LIMIT_MB.
memorylimitmb = 8192

[performance]
# Força o SQL Server a manter a memória alocada, evitando swap.
forceflushtype = 3
traceflags = 3226, 3605, 8048

# =====================================================================
# Network & Connectivity
# =====================================================================

[network]
# Habilita o protocolo TCP/IP
tlsprotocols = 1.2
forceencryption = 0
