#!/bin/bash
set -e

SQLCMD=$(find /opt -name sqlcmd)

if ! $SQLCMD -U sa -P "${MSSQL_SA_PASSWORD}" -q quit 2>/dev/null; then
	echo ignorando certificados
	SQLCMD="${SQLCMD} -C"
fi

$SQLCMD -U sa -P "${MSSQL_SA_PASSWORD}" <<-EOSQL
	CREATE DATABASE ${DATABASE_NAME} COLLATE Latin1_General_BIN;
	GO
	ALTER DATABASE ${DATABASE_NAME} SET RECOVERY SIMPLE WITH NO_WAIT;
	GO
	CREATE LOGIN ${DATABASE_USER} WITH PASSWORD='${DATABASE_PASS}', DEFAULT_DATABASE=${DATABASE_NAME}, CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF;
	GO
	USE ${DATABASE_NAME};
	GO
	CREATE USER ${DATABASE_USER} FOR LOGIN ${DATABASE_USER} WITH DEFAULT_SCHEMA=[dbo];
	GO
	GRANT ALL ON database::${DATABASE_NAME} TO ${DATABASE_USER} WITH GRANT OPTION;
	GO
	GRANT CONTROL, ALTER ON database::${DATABASE_NAME} TO ${DATABASE_USER} WITH GRANT OPTION;
	GO
EOSQL
