#!/bin/bash
set -euo pipefail

# Funções de log estruturado
log_info() {
    echo "ℹ️  $*"
}

log_success() {
    echo "✅ $*"
}

log_error() {
    echo "❌ ERRO: $*" >&2
}

log_warning() {
    echo "⚠️  AVISO: $*"
}

# Função para validar variáveis de ambiente
check_env_var() {
    local var_name=$1
    if [[ -z "${!var_name:-}" ]]; then
        log_error "Variável de ambiente '${var_name}' não está definida."
        exit 1
    fi
}

# Validação de variáveis críticas
check_env_var "ORACLE_PWD"
check_env_var "ORACLE_PDB"
check_env_var "DATABASE_USER"
check_env_var "DATABASE_PASS"
check_env_var "DATABASE_NAME"

echo "ℹ️  Criando estrutura de banco Oracle..."

#FEITO
#CREATE OR REPLACE DIRECTORY "${meta.templateName}" AS '${meta.templatePath}'
#GRANT READ, WRITE ON DIRECTORY "${meta.templateName}" TO "${meta.username}"
# para "criar o banco de dados" (lembrando que tem dois tablespaces)
#/opt/oracle/oradata
#CREATE TABLESPACE "${tablespace.targetName}" DATAFILE '${tablespace.targetPath}' SIZE 1M AUTOEXTEND ON NEXT 100M
#CREATE USER "${meta.username}" IDENTIFIED BY "${meta.password}" DEFAULT TABLESPACE "${meta.defaultTablespace}"
#GRANT ESP TO "${meta.username}" WITH ADMIN OPTION
#GRANT UNLIMITED TABLESPACE TO "${meta.username}"
#ALTER USER "${meta.username}" DEFAULT ROLE "ESP"
#ALTER USER "${meta.username}" QUOTA UNLIMITED ON "${meta.created[i]}"


# depois de restaurar
#fazer o impdp
#NOTA: acho que nao precisa disso: SELECT * FROM "${meta.username}".TOP_FIELD
#UPDATE "${meta.username}".TOP_FIELD SET FIELD_TABLE = TRIM(REPLACE(FIELD_TABLE, '${meta.schema.name}.', '${meta.username}.'))

# limpando as coisas (lembrando que eh para os dois tablespaces)
#DROP TABLESPACE "${tablespace}" INCLUDING CONTENTS AND DATAFILES
#DROP USER "${username}" CASCADE


sqlplus sys/${ORACLE_PWD}@${ORACLE_PDB} AS SYSDBA <<-EOSQL
	CREATE ROLE ESP NOT IDENTIFIED;

	GRANT CONNECT,
	  CREATE SESSION,
	  RESOURCE,
	  ALTER SYSTEM,
	  CREATE VIEW,
	  DATAPUMP_IMP_FULL_DATABASE,
	  DATAPUMP_EXP_FULL_DATABASE
	TO ESP;

	GRANT SELECT ON SYS.COL\$ TO ESP;
	GRANT SELECT ON SYS.OBJ\$ TO ESP;
	GRANT SELECT ON SYS.IND\$ TO ESP;
	GRANT SELECT ON SYS.ICOL\$ TO ESP;
	GRANT SELECT ON SYS.ALL_ARGUMENTS TO ESP;
	GRANT SELECT ON SYS.ALL_INDEXES TO ESP;
	GRANT SELECT ON SYS.ALL_IND_COLUMNS TO ESP;
	GRANT SELECT ON SYS.ALL_OBJECTS TO ESP;
	GRANT SELECT ON SYS.ALL_PROCEDURES TO ESP;
	GRANT SELECT ON SYS.ALL_SEQUENCES TO ESP;
	GRANT SELECT ON SYS.ALL_TABLES TO ESP;
	GRANT SELECT ON SYS.ALL_TAB_COLUMNS TO ESP;
	GRANT SELECT ON SYS.ALL_TRIGGERS TO ESP;
	GRANT SELECT ON SYS.ALL_VIEWS TO ESP;
	GRANT SELECT ON SYS.DATABASE_PROPERTIES TO ESP;
	GRANT SELECT ON SYS.NLS_SESSION_PARAMETERS TO ESP;
	GRANT SELECT ON SYS.V_\$VERSION TO ESP;
	GRANT SELECT ON SYS.GV_\$SESSION TO ESP;
	GRANT SELECT ON SYS.V_\$NLS_PARAMETERS TO ESP;
	GRANT SELECT ON SYS.GV_\$NLS_PARAMETERS TO ESP;
	GRANT SELECT ON SYS.V_\$PARAMETER TO ESP;
	GRANT SELECT ON SYS.GV_\$PARAMETER TO ESP;
	GRANT SELECT ON SYS.DBA_ROLE_PRIVS TO ESP;
	GRANT SELECT ON SYS.DBA_TAB_PRIVS TO ESP;
	GRANT SELECT ON SYS.ROLE_TAB_PRIVS TO ESP;

	CREATE OR REPLACE DIRECTORY DUMPS AS '/local/data/totvs/dumps/';
	GRANT READ, WRITE ON DIRECTORY DUMPS TO ESP;
EOSQL

sqlplus system/${ORACLE_PWD}@${ORACLE_PDB} <<-EOSQL
	CREATE TABLESPACE ${DATABASE_NAME}_DATA DATAFILE '/opt/oracle/oradata/${DATABASE_NAME}_DATA.dbf' SIZE 1M AUTOEXTEND ON NEXT 100M;
	CREATE TABLESPACE ${DATABASE_NAME}_INDX DATAFILE '/opt/oracle/oradata/${DATABASE_NAME}_INDX.dbf' SIZE 1M AUTOEXTEND ON NEXT 100M;

	CREATE USER ${DATABASE_USER} IDENTIFIED BY "${DATABASE_PASS}" DEFAULT TABLESPACE ${DATABASE_NAME}_DATA;
	GRANT ESP TO ${DATABASE_USER} WITH ADMIN OPTION;
	GRANT UNLIMITED TABLESPACE TO ${DATABASE_USER};
	GRANT READ, WRITE ON DIRECTORY DUMPS TO ${DATABASE_USER};

	ALTER USER ${DATABASE_USER} DEFAULT ROLE ESP;
	ALTER USER ${DATABASE_USER} QUOTA UNLIMITED ON ${DATABASE_NAME}_DATA;
	ALTER USER ${DATABASE_USER} QUOTA UNLIMITED ON ${DATABASE_NAME}_INDX;
EOSQL
